### ISSUE TITLE
Drain any remaining activations from `poll_task` until it returns `CoreError::ShuttingDown`

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-node#19] opened 2021-03-01 19:06 UTC
Doesn't need to be this PR but you'll probably want to have some mechanism to drain any remaining activations from `poll_task` until it returns `CoreError::ShuttingDown`. Remaining activations may exist due to replaying a workflow to catch up to the end of history which was already fetched from the server

_Originally posted by @Sushisource in https://github.com/temporalio/sdk-node/pull/18#discussion_r584953075_

**Comment by bergundy** [comment] 2021-03-03 08:30
@Sushisource I tried to implement draining but never got `CoreError:ShuttingDown`, in fact the promise returned from `run` was never resolved or rejected.
See the worker code here: https://github.com/temporalio/sdk-node/blob/aff47fddc0f2de53f52677fc97084139ea268e06/packages/worker/src/worker.ts#L142

Example worker to reproduce:
```
import { Worker } from '@temporalio/worker';

async function main() {
  const worker = new Worker(__dirname});
  const p = worker.run('test');
  await new Promise((resolve) => setTimeout(resolve, 100));
  worker.shutdown();
  await p;
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
```

**Comment by Sushisource** [comment] 2021-03-03 17:42
@bergundy I'll fix this - it's immediately clear to me what the problem is... `poll_task` is stuck blocked on the long poll and never gets a chance to see that the shutdown flag is set. I need some way to interrupt the long poll when that happens. Should be easy.

**Comment by Sushisource** [comment] 2021-03-03 22:58
Should be fixed by https://github.com/temporalio/sdk-core/pull/59

**Comment by bergundy** [comment] 2021-03-04 12:56
After the above is merged, we should update the submodule and create a PR for https://github.com/temporalio/sdk-node/tree/graceful-shutdown

**Closed** 2021-03-09 10:43 UTC
